

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
        

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
