server:
  port: 8089

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-server
              uri: lb://auth-server
              predicates:
                - Path=/api/v1/auth/**
              # filters:
              #   - name: AuthenticationFilter
              #     args: 
              #       requiredRole: PRODUCER
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
