server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: http://localhost:8097/
          predicates:
            - Path=/api/v1/auth/**

management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
