server:
  port: 8089

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: AUTH-SERVER
          uri: lb://AUTH-SERVER/
          predicates:
            - Path=/api/v1/auth/**
      server:
        webflux:
          discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
